spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: zarga.working@gmail.com
    password: Irisviel95
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
